jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://org3c3ac2b9.crm6.dynamics.com/'
        user-name: 'ethanhurst@apjd365online.onmicrosoft.com'
        password-secret: ${{ secrets.MYPASSWORD }}
        solution-name: GithubActionsPipeline
        solution-output-file: 'GithubActionsPipeline.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/GithubActionsPipeline.zip'
        solution-folder: 'out/solutions/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://myenv.crm.dynamics.com'
        user-name: 'me@myenv.onmicrosoft.com'
        password-secret: ${{ secrets.MYPASSWORD }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/GithubActionsPipeline'
        solution-target-folder: 'src/solutions/GithubActionsPipeline'
        token: ${{ secrets.GITHUB_TOKEN }}
