name: Pack

on:
  push:
    paths:
      - contents/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/GithubActionsPipeline‎.zip
          solution-folder: contents
          solution-type: Both
      - uses: actions/upload-artifact@v4
        with:
          name: packed-solution
          path: out/
